version: '3.8'

services:
  app:
    build: .
    ports:
<<<<<<< HEAD
=======
      - '88:88'
>>>>>>> 729dc7d (test: redeploy after path fix)
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    ports:
      - '3306:3306'
    env_file:
      - .env
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
